### ISSUE TITLE
file system docs are in wrong place

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#1048]
A lot of the file system documentation is in the documentation for the `io` library, but should be in the docs for the `system` library.

(I am addressing this, but this bug is to help make sure that I don't forget.)

**Comment by cgay** [comment]
Notes from @housel:

> `<file-stream>` was originally in system, but io contained an implementation of unbuffered I/O used for `*standard-output*` etc, so if you redirected stdout or stderr it was really slow
> So I moved the buffered file I/O into the io library, but left the filesystem access code (including opening named files) in system.

Some languages put their higher-level file operations in their IO libraries so I don't know if we should move the documentation or export `<file-stream>` et al from `io:streams`.  I lean toward exporting from IO.  (Ultimately this is because I lean toward moving `date` and `simple-xml` *out* of `system` and more-or-less making it the `os` library/module.)

**Comment by fraya** [comment]
Commits e8afab3 and 6e74b10 are related with this issue. Could we please consider closing this issue, or perhaps provide more specific details about what actions can be taken?

**Comment by cgay** [comment]
I think this is safe to close. Thanks for those updates...great to see a bunch of bugs being closed.
