### ISSUE TITLE
Cached header engine nodes: Do they work? Are they used?

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#407]
We see places where having a call site cache for method dispatch would be very useful.

Do the cached header engine nodes actually get used? Are they useful? How do they work?

**Comment by housel** [comment]
Yes, they definitely do work. At one point the entry point code used with the LLVM back-end lost track of the per-call-site header, so that only the per-GF dispatch caches could be used. Until this was fixed (in commit ac68a06, part of pull request #1223), the negative performance impact was significant.
